### ISSUE TITLE
Follow redirect when notifying subscribers

### ISSUE THREAD

**Issue by fmfernandes** [rsscloud/rsscloud-server#10]
Hi! We've been trying to debug an issue we're having when trying to subscribe on `rpc.rsscloud.io`. You can check how we were debugging the issue in this repo: https://github.com/scripting/a8c-FeedLand-Support/issues/38. I think it boils down to Notify requests not getting to our server because we have some redirect in place (`http` -> `https`). So, when we receive a `POST` on our notify URL (`/feedupdated`), the cloud server is getting a `301` and thus the `Notify Failed` message shows up in the [logs](https://rpc.rsscloud.io/viewLog). We're using the `feedland.com` domain for that testing.

I think the issue is on this line: 
 https://github.com/rsscloud/rsscloud-server/blob/425aef76f6d3f86cd2760abf03d60dd38bac46f4/services/notify-one.js#L9

Since the response is not in the range 200 ~ 299, the request fails. I believe there's a `followAllRedirects` option that can be set on the `POST` request for that, though not sure if it's the best way to handle the redirect.

There's some example requests I made while trying to debug this issue: https://github.com/scripting/a8c-FeedLand-Support/issues/38#issuecomment-1823238201.

**Comment by andrewshell** [comment]
Thanks for the report. With the holiday this week, I’m not sure I’ll get to this right away. However, I’ll look into it as soon as I can.

**Comment by scripting** [comment]
@andrewshell -- just checking in on this issue. @fmfernandes and I are working together on the new Automattic instance of FeedLand. i've learned a lot on this project, and this is one of the last details we have to take care of before opening it for others to use. really appreciate your help with this. ;-)

**Comment by andrewshell** [comment]
I'm just getting my head back into the codebase. Might be live tonight :-)

**Comment by andrewshell** [comment]
FYI, you can also use the `https-post` protocol, and it will work the same as `http-post` only using https as the domain.

**Comment by andrewshell** [comment]
I haven't heard of any more issues since my deployment.
