### ISSUE TITLE
Add logging to see if XML-RPC is being used

### ISSUE THREAD

**Issue by andrewshell** [rsscloud/rsscloud-server#11]
In version 2.0, I added XML-RPC endpoints to mirror the original rssCloud server. However, I'm not sure that anyone uses them, and even Dave eluded to its deprecation:

> Also, over time we've settled on using plain old HTTP in place of SOAP or XML-RPC, which were provided for in the initial <cloud> element. [#](http://source.scripting.com/#1701264416000)

If anyone still uses XML-RPC I will commit to maintaining support. However, I want to know for sure before I start work on rssCloud Server 3.0

**Comment by scripting** [comment]
I don't believe in "deprecation" but I don't believe the spec ever said everyone has to implement all of the protocols.

**Comment by andrewshell** [comment]
@scripting I haven't decided if I'll remove it, but I'd like to know if it's being used.
