### ISSUE TITLE
Pinging rsscloud.io from HTTPS?

### ISSUE THREAD

**Issue by scripting** [rsscloud/rsscloud-server#9]
I'm trying to ping over HTTPS, and getting an error. I wonder if I'm doing it correctly?

I have an internal routine called cloudPing, this is how I'm calling it.

`cloudPing ("https://rpc.rsscloud.io:5337/pleaseNotify", "http://scripting.com/publicfolder/drummer/dwPublicNotes.opml")`

This is the code for the function.

```
function cloudPing (urlServer, urlOutline) {
	$.post (urlServer, {url: urlOutline}, function (data, status) {
		console.log ("cloudPing: urlServer == " + urlServer + ", urlOutline == " + urlOutline + ", status == " + status);
		});
	}

```

I'm getting an error on the call -- net::ERR_SSL_PROTOCOL_ERROR.

I'm trying to hook up Instant Outlines in Drummer to rssCloud.

**Comment by andrewshell** [comment]
I didn't have SSL configured for rpc.rsscloud.io, so I added it. You should be able to access it via HTTP or HTTPS now. Let me know if this solves your problem.

**Comment by scripting** [comment]
@andrewshell -- no change, getting the same error as before.

**Comment by andrewshell** [comment]
Ah, it looks like SSL is only working on port 443 (default SSL port), so remove the `:5337` or replace it with `:443` and see if that works.

**Comment by scripting** [comment]
@andrewshell  -- that didn't work either.

**Comment by andrewshell** [comment]
Then I'm not sure. It could be a caching issue if it's in the browser (pinging from Drummer). What happens if you go to https://rpc.rsscloud.io/pleaseNotifyForm in a new tab? If I go to https://rpc.rsscloud.io:5337/pleaseNotifyForm (with port 5337) I get the ERR_SSL_PROTOCOL_ERROR message, but not if I go to 443 or without the port.

**Comment by andrewshell** [comment]
Also, you would want to POST to `https://rpc.rsscloud.io/ping` for pinging. `/pleaseNotify` would be if you were subscribing to pings.

**Comment by scripting** [comment]
@andrewshell  --

Changing the URL got rid of the SSL error.

cloudPing ("https://rpc.rsscloud.io/ping", "http://scripting.com/publicfolder/drummer/dwPublicNotes.opml")

and the message got through to the subscribe, so the show is on the road now!

Thanks for your help!

**Comment by andrewshell** [comment]
Glad it's working. I'm happy to see you using rssCloud for OPML files :-)
